### PR TITLE
deps: k8s: 1.24.7 -> 1.25.3

### PR DESCRIPTION
**Pull request by fromanirh**
trivial dep bump, but with a tail of updates triggered by the fact kube 1.25+ now requires ginkgo v2

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
CI failure is real and we need updates to our e2e tests

**Comment by fromanirh** [comment]
kube 1.25 pulls ginkgo v1. This means that before being able to update to kube 1.25.z, we need to port our tests to ginkgo v2 (or alongside)

**Review by swatisehgal — APPROVED** [review]
/lgtm

When I reviewed https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/137 yesterday, I was wondering why we were not moving to the latest version but then thought that we were intentionally moving to the next version :) 

Anyway, I am definitely in the favor of moving the latest version! Thanks for taking care of this work.

**Comment by fromanirh** [comment]
> /lgtm
> 
> When I reviewed #137 yesterday, I was wondering why we were not moving to the latest version but then thought that we were intentionally moving to the next version :)
> 
> Anyway, I am definitely in the favor of moving the latest version! Thanks for taking care of this work.

That's a very good point. I wanted to have the intermediate step recorded (release-0.8), that's the main driver

**Pull request merged**
