### PR TITLE
e2e: try again to simplify/deflake smart poller tests

### PR DESCRIPTION
**Pull request by ffromani**
Another attempt to simplify and at the same time deflake the longstanding unreliable smart poller test.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by Tal-or** [comment]
I would suggest to cancel the update by interval in this test. (we can set `sleepInterval = 0` to imply no update on interval basis)
This way we can guaranteed that when an update received it received for the right reasons, and we don't need to schedule the pod creation between intervals.

**Comment by ffromani** [comment]
the work to disable polling, which requires quite a lot of infra reworking, is underway in #153

**Review by swatisehgal — APPROVED** [review]
I see there is work in progress to tackle cases where we tackle cases for polling and evented separately for more focused testing. For now, I think we can proceed and merge this.

 /lgtm

**Comment by ffromani** [comment]
> I see there is work in progress to tackle cases where we tackle cases for polling and evented separately for more focused testing. For now, I think we can proceed and merge this.
> 
> /lgtm

yes, the two efforts complement each other. Thanks!

**Pull request merged**
