### PR TITLE
bump to k8s 1.27

### PR DESCRIPTION
**Pull request by Tal-or**
This PR also contains code changes in order to support the API changes that has done for `podresourceapi` and `cpuset` packages.

### CODE REVIEW

**Comment by ffromani** [comment]
perhaps is a bit too early to bump to 1.27. Also, I think we should also bump our CI (can be done on a later PR) to run on top of 1.27

**Comment by Tal-or** [comment]
np. it can wait

**Comment by ffromani** [comment]
before than this, we will probably need to bump the toolchain to golang 1.20

**Comment by ffromani** [comment]
need a rebase

**Comment by Tal-or** [comment]
The latest changes have no simple resolution. Are we planing on bumping soon?
If not, I suggest to close this one

**Comment by ffromani** [comment]
sure, we can just close and reopen later

**Comment by Tal-or** [comment]
Closing according to latest comments

**Pull request closed without merging**
