### PR TITLE
Generate semver compatible versions from tags.

### PR DESCRIPTION
**Pull request by jlojosnegros**
Use git-semver tool to generate semver compatible versions for
development commits.

Add tools.go file to track dependency of git-semver as it is a tool just
used to build purposes.

See: issue #83

### CODE REVIEW

**Comment by fromanirh** [comment]
```
Run RTE_CONTAINER_IMAGE=${RTE_CONTAINER_IMAGE} RUNTIME=docker make image
make: /home/runner/go/bin/git-semver-v1.0.0: Command not found
```

**Comment by fromanirh** [comment]
I'm not sure we want to go down the `bin-go` path

**Comment by jlojosnegros** [comment]
I think it is a nice way to keep the dependency tracked and easy to use without requiring any special operation neither locally nor in Ci.
If not using bin-go or something similar, should we go then for a shell based solution?

**Comment by fromanirh** [comment]
> I think it is a nice way to keep the dependency tracked and easy to use without requiring any special operation neither locally nor in Ci. If not using bin-go or something similar, should we go then for a shell based solution?

considering how invasive (in this context) adding bin-go is, and considering we are unlikely to add extra deps (nothing else on the radar), let's evaluate how hard is to build `go-semver` locally and to use it directly

**Comment by fromanirh** [comment]
like: https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/90

**Comment by jlojosnegros** [comment]
Well I do not think bin-go is so invasive cause It just helps automatizing the process to add or update a dep, but it is not needed for build them at all, but ok.  I will go with the #90 solution

**Pull request closed without merging**
