### PR TITLE
toolchain: update toolchain to 1.20

### PR DESCRIPTION
**Pull request by jlojosnegros**
Update go toolchain to 1.20.7

### CODE REVIEW

**Comment by ffromani** [comment]
thanks for this update! I see you are both updating the toolchain and updating deps, what's the benefit of this? can we split in 1. updating the toolchain and 2. updating the deps?

**Comment by jlojosnegros** [comment]
> thanks for this update! I see you are both updating the toolchain and updating deps, what's the benefit of this? can we split in 1. updating the toolchain and 2. updating the deps?

You're right, better to update deps in another PR if needed at all.

**Comment by ffromani** [comment]
LGTM, but let's cut 0.14.0 before

**Review by ffromani — APPROVED** [review]
LGTM

**Pull request merged**
